### ISSUE TITLE
幾點問題

### ISSUE THREAD

**Issue by endermoon** [langyo/MCBBS-Client#1]
1. MCBBS.NET 是 http 的，這顯然不安全，這個 client 可有加密方面的打算？
2. 目前的規劃是現做哪一方面？
3. 是否應該寫寫項目 wiki？
以上。祝好。

**Comment by endermoon** [comment]
哦，忘記說了，項目文檔其實用 ReadTheDocs 或 Gitbooks 更好

**Comment by langyo** [comment]
### 关于第一个问题
我早就在考虑这个事情了，但我目前没有什么办法让原本的 http 请求升级为 https 请求

等代码稳定下来后再说吧，反正我有加入插件功能，凭插件我可以再开发额外的 https 协议升级插件

目前我能想到的唯一一个能够借鉴的项目是 lantern，我只看见这一个软件是把经过它的 http 连接升级到 https 的
### 关于第二个问题
electron + react native
### 关于第三个问题
这个项目目前还非常不稳定，随时都可能有大的结构更改，所以我目前暂时只能先把 wiki 与源码同放在一块

直到项目结构基本稳定之前，我没有办法也不会去写 wiki，毕竟一旦有大的更改，之前写的 wiki 几乎就全部作废了

以及，gitbook 这类东西是在项目开发的最后做的……
