### ISSUE TITLE
[建议]不推荐使用浏览器插件

### ISSUE THREAD

**Issue by jihuayu** [langyo/MCBBS-Client#11]
- 浏览器插件需要等待网页渲染（加载）完毕再执行js代码，十分缓慢。（应该是这样，测试时主页一般会有2-3s延时）
- 浏览器插件执行代码有问题，对于某些网页（如mcbb主页），获取html元素代码不能正常执行（推断）。
- 浏览器插件无法在桌面/浏览器中调试。
- 书写步骤繁琐。
--------
综上，不建议使用浏览器插件作为数据获得途径。

**Comment by langyo** [comment]
回答一下……
- 有关第一个问题。你的问题提的很好，确实有严重的性能问题。不过你注意到没有……我用浏览器插件纯属就为获取论坛页面数据，压根就不会拿出来渲染（如果后台仍然在渲染的话，我会加入一些 css，强行告诉插件劳资不要渲染……）
- 有关第二个问题。我有点纳闷，这插件既然提供了 execJavaScript 函数，怎么就不能正常执行获取 DOM 元素数据的代码了？……
- 有关第三个问题……我也很无奈啊，但有什么更好的办法吗？
- 有关第四个问题……你看看隔壁 electron 写的其实不也挺繁琐的嘛……（虽然我准备要改写逻辑，准备不用 <webview> 了，因为我耍不过 React）

**Comment by jihuayu** [comment]
-  在实验中发现 execJavaScript 可以获得某些网站的html，比如[archiver](http://www.mcbbs.net/archiver/)，但是相同的代码不能获得mcbbs主页的html。
- mcbbs防御脚本关闭后是不是可以直接get到html。
- 第4个是凑数理由。

**Comment by langyo** [comment]
防御脚本的事情……其实我蛮头疼的……

get？……但是只凭 ionic 本体是没有这样的 API 的，真要弄还是得依赖插件

我对移动端框架的选取已经简化到只有三个要求了：
- 能执行 JavaScript
- 能控制我想显示的东西
- 能自行创建、控制虚拟浏览器

我真想发个无奈的表情

**Comment by jihuayu** [comment]
[ionic-http插件](https://github.com/silkimen/cordova-plugin-advanced-http)
关于虚拟浏览器我再研究一下。
可以考虑将解析后的数据存在某些地方，当防御脚本打开时，在那里解析。

**Comment by langyo** [comment]
我还有两个备用方案，你看一看；这两个方案可以配套使用
1. ionic 的插件是基于 cordova 的，所以我搜了 cordova，发现这玩意其实是 phonegap 项目下的一个分支
phonegap 也类似 ionic，是一个移动端开发框架，你帮我看下哪边的更好用？
2. 如果只下载 HTTP 的话，你可以看下 JSDOM 这个库，说不定能用上

**Comment by jihuayu** [comment]
又研究了一下发现了，
- 在内置浏览器中可以输出获得的html，但是该html无法返回应用。
- 静态的如数字，字符串可以成功的返回。
- 怀疑是`execJavaScript`执行是异步的。

**Comment by langyo** [comment]
只有 MCBBS 不能被获得？

奇怪……

你试试让内置浏览器运行下在 scripts/forumWorker/pageParser/ 下的东西？例如随便找个主题，运行 watchThread.js

（注意，scripts 下的 js 都是没编译过的，如果你嫌麻烦不想额外修改 package.json 进行编译，你可以直接用 native/electron/scripts/ 文件夹下的编译好的代码）

**Comment by jihuayu** [comment]
@langyo 
已发现原因，由于内置浏览器返回的html太多了，导致返回失败。

**Comment by langyo** [comment]
那太好了

既然数据太大，那我们干脆就把对数据的处理直接在 evalScript 里进行吧

请你帮我看下，如果使用 evalScript 引用本地 js 文件，返回值应该怎样返回比较好（我只知道如何让 js 公开 module.export，但不知道这玩意能有什么返回值）

或者，变通的方法，先让它执行，不弄什么回调函数，然后你执行这一句：
    executeScript(window, 'module.export', n => console.log(n));
    （上头这句只是大概表达意思）

**Comment by jihuayu** [comment]
evalScript引用本地js文件比较困难，
- 如果写的是相对路径，那么是根据浏览网页相对的。
- 如果写网址，可以！
- 如果写文件路径，由于打包机制比较迷，我也不太确定是否可以。
