### ISSUE TITLE
[问题]移动端与pc端的网页html布局不一致

### ISSUE THREAD

**Issue by jihuayu** [langyo/MCBBS-Client#12]
移动端与pc端的网页ui不一致，考虑到这个问题有以下解决方案：
- 写两份布局解析。
- 将两个浏览器头部浏览器信息改为一致。
------------------
暂时不知道怎么改浏览器插件的浏览器头部。

**Comment by langyo** [comment]
我对此早有计划（早在 2018 年 10 月开坑的时候就想好了）……

响应式

更具体来讲，我只需要写一份页面就行了，而不同的 UI 元素 在不同分辨率下会选择性地呈现出来

哦还有……你上一个问题既然解决了，要不要考虑把实验成果 pr 到我这里？…… XD

~~说白了，我也想研究下·你写的东西~~

**Comment by jihuayu** [comment]
不，我是说，mcbbs在手机端和pc端的ui不一样。
考虑到桌面和手机用户的习惯，我觉得需要两套布局。
成功过一会pr，其实大部分都是实验，没实质性内容。

**Comment by langyo** [comment]
嗯……那我写两套 UI 好了

不过放心，工作量不多，因为 React 有一种说法叫组件复用……

我写的一大坨东西是可以重复利用的……
