### ISSUE TITLE
[建议]是否把移动端和pc端项目合二为一

### ISSUE THREAD

**Issue by jihuayu** [langyo/MCBBS-Client#13]
这是一个啥都没有的参考项目[参考项目](https://github.com/grosa1/ionic_electron)。
这是一个比较复杂的参考项目[参考项目](https://github.com/guobin211/all-in-one)。
可以把ionic项目和electron项目合起来，之前也说过响应式布局，但是有这个问题：
> ionic浏览器插件无法在electron中运行（应该）。

是否有这种合二为一的想法，如果有我可以先试验一下。

ps：~~mcbbs论坛有登陆不需要验证码的bug~~

**Comment by langyo** [comment]
……我现在好像就正在这么做…………

~~你说啥？论坛不要验证码？怎么做到的？！~~

**Comment by jihuayu** [comment]
~~只需要在登陆时把pc端ui切换成移动端~~
目前工程文件真的大。
我接下去工作可能会主要集中在，功能试验，ui开发，及论坛解析。
我觉得我们可以用服务器解析网站，把解析后的数据放到免费的数据库[500MB](https://mlab.com/home)，虽然速度慢一点，但是对于搜索有很大的好处，也更利于客户端的书写？

**Comment by langyo** [comment]
~~诶我去你还给我找了个免费的数据库……~~

我其实……也早就想好了如何解决访问论坛卡慢什么的问题
每个运行客户端的机器，在获取到新的页面的数据并解析后，会自动上传到 [Google Firebase](https://firebase.google.cn/)
其他用户在浏览论坛时，就会优先提取从 Firebase 数据库中预存储的信息
这样还能带来两条额外的好处，一是论坛崩了还能继续看帖子，二是会保留所有的帖子修改记录（也就是说你甚至可以利用此查看某些历史悠久帖子以前的内容）

~~其实我们目前要做的事情好像也就是……功能试验，ui开发，论坛解析……~~

**Comment by langyo** [comment]
顺带一提……Google Firebase 看起来其实比你那个数据库要方便许多……因为人家还额外提供了专用的 API 库……

~~你给的那玩意我收藏了~~

**Comment by jihuayu** [comment]
如果顺利我可能考虑多支持一些网站，比如mcmod或者其他的mc论坛。  
~~不过我现在被热更新插件逼疯了。~~

**Comment by langyo** [comment]
可以考虑
(我原本就有这个打算来着，想同时让客户端能够访问百度贴吧和 MinecraftForum 啥的)

先把最基本的事情做出来再说吧...

**Comment by jihuayu** [comment]
热更新插件与新版ionic不兼容，我已经暴毙。
改用微软的热更新了！

**Comment by langyo** [comment]
嗯，CodePush，你值得拥有

**Comment by jihuayu** [comment]
暂时停止制作移动端。
