### ISSUE TITLE
[问题]桌面端的界面大小

### ISSUE THREAD

**Issue by jihuayu** [langyo/MCBBS-Client#14]
做面端界面应该多大？是固定还是可以拖大？
（个人建议固定）
感觉现在大小看起来好别扭。
我觉得大概这么大比较合适（1600*900）
![大小](https://user-images.githubusercontent.com/32858525/52910756-1bf66200-32d7-11e9-90de-c510cfb442ea.png)
另外，调试electorn项目，编译要好久时间，有没有其他方法？

**Comment by langyo** [comment]
我……

先回答第一个问题，我设置成固定大小 800 * 600 了，你怎么居然还能把窗口拉大？！

再回答第二个问题，那是你用错指令了……
```
npm run watch
```
亲，别运行 build 好不好……那样会完全重新编译……
使用 watch 就能做到增量更新，每次修改文件都会编译，时间基本上每次都小于 3 秒

**Comment by jihuayu** [comment]
怎么感觉他只监视一个文件的更改（或者不全）？

**Comment by langyo** [comment]
800 x 600 固定
这同时也是网易云音乐的 PC 端播放器的默认窗口大小
毫无违和感
我估计没啥人用小于 1024 x 768 分辨率打开客户端吧……

**Comment by langyo** [comment]
哦还有……你发现没，我更改了 issue 模板

以后按着那个模板来好不好嘛

**Comment by jihuayu** [comment]
好吧。那就是只做一种ui风格？就是800 x 600？

**Comment by langyo** [comment]
桌面端就这么规划，以后 UI 会根据情况升级

例如~~违反 Material Design 规范~~修改背景图片和颜色啥的

**Comment by langyo** [comment]
我大清早赶到教室里看到你的 commit 了……

诶我去你居然真的把它改成 1600 * 900 的了……

你要知道我在教室里的机器屏幕分辨率连 1440 都没到啊……（虽然可以调整，但放幻灯片时会被骂）

**Comment by jihuayu** [comment]
不急，我今天改回去，之后有更改会放到changelog里面，你可以只看changelog。

**Comment by jihuayu** [comment]
有空可以看一下我的[开发计划](https://github.com/jihuayu/MCBBS-Client/projects/1)。
不知道你有没有写的权限，有的话可以改一改。

**Comment by langyo** [comment]
> 有空可以看一下我的[开发计划](https://github.com/jihuayu/MCBBS-Client/projects/1)。
> 不知道你有没有写的权限，有的话可以改一改。

没权限读写

不过后续我会给你个 collaborator 权限，你大概可以更改我这里的 project
