### ISSUE TITLE
[问题]这是啥玩意

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#21]
**描述**
谁能给我解释下这新加的部分是什么玩意……
@jihuayu 

**为什么要提出这个问题**
因为已经有个 localDatabase 了，我看里头源码长的很奇怪，也是操作数据库……
重复了好不……

**截图**
![b9202da303f9c7676ec39.png](https://miao.su/images/2019/02/21/b9202da303f9c7676ec39.png)

**使用的平台以及客户端信息**
 - 操作系统: Windows NT 7
 - 客户端版本 0.2.4

**Comment by langyo** [comment]
![b78b316316a7ab94e0510.png](https://miao.su/images/2019/02/21/b78b316316a7ab94e0510.png)

以及这测试又是啥……

**Comment by simon300000** [comment]
我有一个提案
用 Graphviz 画拓扑图，这样如果有更多贡献者都能更容易的参与工作，并且防止这样的情况发生

**Comment by langyo** [comment]
> 我有一个提案
> 用 Graphviz 画拓扑图，这样如果有更多贡献者都能更容易的参与工作，并且防止这样的情况发生

Graphviz……

我等下查下，看下·能不能用

**Comment by langyo** [comment]
> 我有一个提案
> 用 Graphviz 画拓扑图，这样如果有更多贡献者都能更容易的参与工作，并且防止这样的情况发生

这种情况倒是没法防止，除非将所有贡献者圈起来天天在微信群或 QQ 群之类的地方天天开会……

我都做不到抽出时间去开什么会，整天忙死了都，更何况是你们呢……

我现在只能做到尽量让你们多看看 projects……多看看 docs……有问题尽可能先发个 issue 问问大家的意见……

至于 Graphviz……拿它写 docs 确实挺不错的，但是它做不到协调各贡献者

**Comment by simon300000** [comment]
Graphviz 是纯文本，和git配合起来应该很好用
不过这个现在倒是不重要

我个人，个人的感觉，这个Project的结构很特殊，没有明显的entry，我一开始的时候都不知道代码该从哪里开始读。（当然也是因为我个人技术水平原因）

希望在这里话痨不会妨碍到你→_→

**Comment by langyo** [comment]
> Graphviz 是纯文本，和git配合起来应该很好用
> 不过这个现在倒是不重要
> 
> 我个人，个人的感觉，这个Project的结构很特殊，没有明显的entry，我一开始的时候都不知道代码该从哪里开始读。（当然也是因为我个人技术水平原因）
> 
> 希望在这里话痨不会妨碍到你→_→

不会的，在这种时候还有人能陪我说说话我其实挺满足了

最近真的忙的要死，一大堆作业堆了又堆，我确实特别想找点我感兴趣的事情去做做，但无奈没时间

一天到晚抱着个《Orange's 一个操作系统的实现》，但我上机的时间只够我写一点点有关客户端的代码的，然后就再也挤不出时间去写操作系统了（另外还有个 CPU 的坑我也没来得及去做）

我会考虑下 Graphviz 放在哪里用，很大可能我会为此专门去找个显示 doc 用的东西（例如 Gitbook）

**Comment by simon300000** [comment]
某种意义上也挺好
有更多时间思考

**Comment by simon300000** [comment]
我的妈呀！
没想到你特意搞一个scripts就是因为需要babel翻译！？！？
我的天啊怪不得没有entry

**Comment by jihuayu** [comment]
这个是个人设置。
我想把个人设置和数据分开。

**Comment by langyo** [comment]
> 这个是个人设置。
> 我想把个人设置和数据分开。

原本的数据库里不是已经有个叫 local 的子数据库了嘛……

**Comment by jihuayu** [comment]
最近开学有点忙，可能回复不是很及时。
我是想这样，一个数据库太大不好调试。

**Comment by simon300000** [comment]
还是vue好用
weex一波流
