### ISSUE TITLE
[特性]有关苦力怕 Live2D 看板娘

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#22]
**对需求的简明描述**
![huaji](https://cdn.jsdelivr.net/gh/xb2016/kratos-pjax@0.3.8/static/images/smilies/huaji6.png)
这个计划早就有了，但是一直没找到可以入眼的例子，所以没好意思提出来
不过呢，我找到了几个人的博客，他们的页面弄得挺好的：
https://www.fczbl.vip/946.html/comment-page-12#comment-3856
https://imjad.cn/archives/lab/add-dynamic-poster-girl-with-live2d-to-your-blog-02
https://imjad.cn/archives/lab/add-dynamic-poster-girl-with-live2d-to-your-blog-03
尤其是后两个链接对应页面下的血小板，那是真的精良，点两下居然还会跳
~~我才不会说 2233 娘那个链接不断换装有裸 * 福利呢~~

现在是时候筹划这件事了

**描述你想要的东西**
征求画师，画苦力怕娘的 Live2D 图片素材

**其它要说的话**
@simon300000 @jihuayu

**Comment by simon300000** [comment]
福利草。。。

**Comment by simon300000** [comment]
作为一个插件→_→？

**Comment by langyo** [comment]
> 作为一个插件→_→？

对，作为一个插件
