### ISSUE TITLE
[特性] 有关启动窗口以及热更新的规划

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#23]
**对需求的简明描述**
为了能使客户端的更新等操作更具弹性，所以我有以下的规划：
- 在用户手中的发行版本里最一开始只能看得到 index.js 这一个 js 文件，用于启动 Electron 进程
- bundle 文件会经过再三优化（说白了就是 npm run build 比 npm run watch 多一个 uglifyjs 尽可能精简脚本），然后上传到可直连的文件服务器上
- index.html 里将写入内嵌的 JavaScript，用以获取、执行 bundle；如果找不到 bundle，它也负责报错（警告框 + 退出程序）
- electron 版本的启动将带有预启动窗口，鼠标穿透（也因此要考虑启动图的事情了）
    此窗口载入后，有检查并下载最新 bundle 的职责；如果没有 bundle 也连不上网，弹警告框；如果发现 bundle 不为最新，它将负责更新并显示进度；如果发现不为最新且连续下载失败，则给出两个通道，一个是从旧版 bundle 启动，另一个是尝试重新下载（关闭程序按钮也是得有的）

**其它要说的话**
1. 问下谁有能用的寄放文件的服务或服务器？……
2. 启动图怎么办？……
3. ……你们对这些更改有别的意见不？
@simon300000 @jihuayu

**Comment by simon300000** [comment]
我有服务器，每个月3TB流量 位置东京

**Comment by langyo** [comment]
> 我有服务器，每个月3TB流量 位置东京

![.](https://camo.githubusercontent.com/ee6b819123e031d11b6aee55a9bdff389507b3ff/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f7862323031362f6b7261746f732d706a617840302e332e382f7374617469632f696d616765732f736d696c6965732f6875616a69362e706e67)
