### ISSUE TITLE
[特性] 改造原本的测试窗口

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#31]
**对需求的简明描述**
![11c6dd.png](https://miao.su/images/2019/03/07/11c6dd.png)
![24262f.png](https://miao.su/images/2019/03/07/24262f.png)
我想改一下测试功能，让它用于 HTTP 发包调试
@jihuayu 问下你的意见

**其它要说的话**
卡片地址：https://github.com/langyo/MCBBS-Client/projects/5#card-18212183

**Comment by langyo** [comment]
@jihuayu

**Comment by simon300000** [comment]
写需要的function然后挂到window下面
然后直接在console 做一部分debug，会不会比较方便简单？

**Comment by langyo** [comment]
> 写需要的function然后挂到window下面
> 然后直接在console 做一部分debug，会不会比较方便简单？

如果要做你所说的这个东西的话，其实有更好一些的做法，那就是在 Electron 外围写检测崩溃的代码，控制台报错会立即弹出预先设计好的窗口

然而奇怪的是，Electron 无法正常捕捉其创建窗口的错误

**Comment by jihuayu** [comment]
测试功能就是用于存放暂时需要谈论的内容，你改掉就可以。
