### ISSUE TITLE
[特性] 为 HTTPS 提供支持、为界面使用路由（router）以及自定义窗口的提议

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#32]
**对需求的简明描述**
### 有关第一个问题：为 HTTPS 提供支持
这个问题其实由来已久，~~而且它是第一个本项目的 issue~~
#1 @endermoon 
我已经找到了个似乎可行的方案，放链接：
https://github.com/getlantern/httpseverywhere
https://www.eff.org/https-everywhere
这似乎就是从本地升级 HTTP 协议到 HTTPS 协议的方案，以浏览器插件的形式发布。
我不知道这个东西的可行性，所以还是想问下你们，如果有实现的必要或意义，我就把它加入 Projects 中的 TODO 里了。

### 有关第二个问题：使用路由（router）
相信你们应该看过 mainViewRender 的代码了吧？
而且我敢保证你们一定已经看吐了，因为各种组件嵌套的实在是太乱了，为了个标签页写了一大堆的鬼玩意……
![c26837ba84a20607605f4.png](https://miao.su/images/2019/03/07/c26837ba84a20607605f4.png)
所以我在考虑使用一个可能对你们来讲很新鲜的玩意—— react_router。
https://github.com/ReactTraining/react-router
https://reacttraining.com/react-router/web/guides/quick-start
这玩意的用途就一句话：在单页面应用中，路由可以把某个 URL 指向特定的 React 组件上。
但这玩意，至少对我来讲其实是很不熟悉的东西，而且如果用它会大改原有的已经稳定运行的代码，很容易写崩。
所以我想问问你们的意见。

### 有关第三个问题：自定义窗口
这种事情其实我去年已经做过了，但是因为出了莫名奇妙的 Bug 而放弃了（旧代码还在，此仓库的 0.2.1 分支就是了）
现在我要重新动用了，因为我找到原因所在了……（其实就是 Material UI 库改动了 React Desktop 的默认 CSS 样式导致的）
https://github.com/gabrielbull/react-desktop
https://reactdesktop.js.org/
也问问你们，该不该用？
~~如果用了的话，那 800 * 600 的固定窗口大小问题也可能会为此有所改动，很可能能够改为随着屏幕分辨率动态决定~~

**其它要说的话**
@simon300000 @jihuayu @InitAuther97 @siiftun1857 @switefaster @SmokeyDays @Yaossg @SPGoding 
突然@一大波人
（因为这次的变动实在是太大了，很可能会把项目往死里推）

（本人最近确实很忙，不一定能及时回复，见谅！）

**Comment by simon300000** [comment]
直接用https访问论坛会出问题，某些css和js消失掉，没研究怎么回事
不过支持https到底是什么意思呢？

**Comment by langyo** [comment]
> 直接用https访问论坛会出问题，某些css和js消失掉，没研究怎么回事
> 不过支持https到底是什么意思呢？

你是指？……

**Comment by simon300000** [comment]
“支持https”
这是什么意思？
论坛某种意义上的确部分支持https啊？

**Comment by langyo** [comment]
> “支持https”
> 这是什么意思？
> 论坛某种意义上的确部分支持https啊？

论坛现在支持以 HTTPS 访问了？

**Comment by simon300000** [comment]
你直接加个https试试？我可以的
要是论坛没开443那你这个插件也没用啊

发自我的 iPhone

**Comment by langyo** [comment]
> 你直接加个https试试？我可以的 要是论坛没开443那你这个插件也没用啊 发自我的 iPhone
> […](#)
> 在 2019年3月8日，下午1:46，伊欧 ***@***.***> 写道： “支持https” 这是什么意思？ 论坛某种意义上的确部分支持https啊？ 论坛现在支持以 HTTPS 访问了？ — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or mute the thread.

无法直接以 HTTPS 访问论坛

**Comment by simon300000** [comment]
我可以
https://www.mcbbs.net/home.php?mod=space&uid=155499
不过证书不对
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/12656264/54013946-eea22300-41b5-11e9-920f-80dc1eef1172.png">
以及没有css

不过既然你无法用https访问论坛，那你用那个插件也没有用啊→_→？

**Comment by simon300000** [comment]
我可以
https://www.mcbbs.net/home.php?mod=space&uid=155499
不过证书不对
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/12656264/54014086-62dcc680-41b6-11e9-9b6a-77f802289afe.png">
以及没有css

不过既然你无法用https访问论坛，那你用那个插件也没有用啊→_→？

**Comment by langyo** [comment]
> 我可以
> https://www.mcbbs.net/home.php?mod=space&uid=155499
> 不过证书不对
> <img alt="image" width="1792" src="https://user-images.githubusercontent.com/12656264/54014086-62dcc680-41b6-11e9-9b6a-77f802289afe.png">
> 以及没有css
> 
> 不过既然你无法用https访问论坛，那你用那个插件也没有用啊→_→？

我好纳闷啊，那蓝灯是怎么做到 HTTP 转 HTTPS 连接的？

**Comment by endermoon** [comment]
1. 论坛的 SSL 支持问题三言两语很难说清楚，等我有时间再说；
1. React Router 这个对我来说并不新鲜，我觉得可以，毕竟现在还属于 0.x 状态，还没有第一个正式版本，有些东西或许可以去大胆尝试，但既然是对你来说没怎么用过的技术，要提防可能留下的在以后发生的 bug；
1. 自定义窗口在不产生新 bug 和大量代码工作量的情况下当然是好的，我不发表意见。
~~所以最后其实只写了一点真正有用的东西~~

**Comment by endermoon** [comment]
我料想 HTTPS everywhere 的工作原理主要是獲取網站是否支持 HTTPS，如果支持就轉發到 HTTPS，因此 HTTPS everywhere 對本身就不支持 HTTPS 的網站來說沒有什麼作用。

**Comment by simon300000** [comment]
我同意，MCBBS似乎不（完整？）支持https，HTTPS everywhere自然也就没什么用了。
而且你要是想用https，直接get https的url就可以了吧，这个插件应该不需要

**Comment by langyo** [comment]
那么 HTTPS 就暂时不予考虑了，等论坛能完整支持 HTTPS 再说
