### ISSUE TITLE
[讨论] 有关使用 capacitor 框架的提议

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#34]
**简要说明为什么要发起这个讨论**
我无意间又看到了[这个玩意](https://capacitor.ionicframework.com/)。
不禁想吐槽两句，这 Ionic 的贡献者们都这么能肝的么……都把魔爪伸向 Electron 了啊……

  **详细的讨论大纲或正文**
出于以下几点，我在考虑使用这个框架：
1. 它同时支持 Electron 和 Ionic，这也许能够解决本项目目前的奇怪的代码结构问题，并且还能做到只写一次代码、只转译一次即可……
2. 这个项目也还处于测试之中，不过如果我们先行用起这个框架，兴许能成为圈子里使用这个框架制作出完整应用的带头项目
3. 这个框架本身依赖于两个已经很成熟的框架，一个是 Cordova 框架（Ionic 本身也依赖于此），另一个是 Electron 框架（不解释，相信贡献者们应该都很熟悉了）
4. 走心的 [docs](https://capacitor.ionicframework.com/docs/)（P.S. 好像还不太完整，但能在 Beta 时期就写出有相当水平的 docs 着实不易）

  **补充的细节**
我还有一些顾虑，所以得问问你们的意见，确定下究竟可不可行：
1. 本人就连 Ionic 本身的应用都没成功调试启动过，对这个新的框架也就很有顾虑，不知道是不是和 Ionic 的调试方式一样~~复杂麻烦~~奇怪（可能做多了移动开发的人们就不会有这样的顾虑，XCode 和 Android Studio 玩的那么熟还怕啥，对吧……）
2. 这个框架也提到了，它们对 Electron 框架的支持并不是太全，我不知道换了之后是不是就连 HTTP 请求都不能发了（虽然要想强行让它支持，文档里也给出了制作插件的方法）
3. Cordova 框架到底能不能发送 HTTP 请求，我对此仍然有抱有很大的疑惑，毕竟我从没成功调试过 Ionic 应用，希望能有人教教我怎么搞

  **其它要说的话**
@simon300000 @jihuayu @InitAuther97

**Comment by simon300000** [comment]
我觉得可以尝试→_→
不过我在模拟考，时间不是很多，不能给出一些实质性的帮助…
如果真行的话，那是不是可以考虑通过css来控制手机/桌面

**Comment by langyo** [comment]
> 我觉得可以尝试→_→
> 不过我在模拟考，时间不是很多，不能给出一些实质性的帮助…
> 如果真行的话，那是不是可以考虑通过css来控制手机/桌面

有比 CSS 更好的东西

如果你仔细看过我写的东西，你会发现我将 CSS 样式写进了 jsx 里，导出 React 元件时使用了 withStyles 函数将样式自动绑定了上去

withStyles 这个函数来源于 Material-UI 库

（你如果闲着没事，可以帮我看看这玩意能不能正常创建应用……三个平台都得测试：Electron、Ionic Android、Ionic iOS）

**Comment by langyo** [comment]
再次看了下这个框架，它对 Electron 框架支持得并不好，文档就只有一页

这个只能作为未来的提案暂时先搁着，等这个框架成熟之后再作讨论

**Comment by simon300000** [comment]
文档就只有一页23333

**Comment by InitAuther97** [comment]
一页233333糊弄鬼呢 不用
