### ISSUE TITLE
关于gitignore和babel打包

### ISSUE THREAD

**Issue by simon300000** [langyo/MCBBS-Client#4]
我在“看”的时候发现这些bundle什么的应该不需要记录进git版本控制呀→_→

在gitignore里注释掉有什么原因吗？

https://github.com/langyo/MCBBS-Client/blob/e7db226fbf4dcd51c194c54cb1cdf375c109544a/.gitignore#L154

**Comment by langyo** [comment]
~~我难道会说这其实是为了防止编译失败打不开软件故意把各种 bundle 留下的么……~~

我会考虑改进下 bundle 机制，但不会删除，原因有以下几点

1. 如果未转译的代码写错了，如果仍然想继续调试之前原本转译正确、使得客户端能够运行的版本，留下 bundle 是很必要的。
2. 这源于我特殊的编程环境。这三个月下来，我都是在使用学校讲台桌的电脑进行编程的。学校的设备有个尿性，关了机之后会回滚数据到之前的状态，你往硬盘里保存的东西是不会留下来的。而在学校中的电脑有随时可能被关闭的风险（大多都是任课老师不知情而关闭），如果不将 bundle 留下来，每次清空数据后重新恢复编程环境时便又要花费相当的时间完全重新转译，耗时耗力。
3. 这是为未来的自动更新功能而考虑（没想到吧？我早就想到这里了）。在未来的代码中，我会往项目根目录添加一个 updata.json 配置文件（访问的地址大概是 https://langyo.github.io/MCBBS-Client/updata.json ），这个 json 会直接指向那些转译/打包好的脚本文件（不用麻烦客户端本身进行转译了，毕竟 babel 其实是个很占用系统资源的东西，能尽可能考虑到用户还是多考虑下吧，不要做那些浪费资源的事情）。

如果没有别的问题的话，你就关闭吧……

**Comment by langyo** [comment]
顺带补充下， .gitignore 把 bundle 忽略掉那个语句错了，我这就改……

**Comment by simon300000** [comment]
1. 写错了不是有git吗→_→
2.a. 开机F8会不会有用hiahiahia
2.b. 有没有可能用云编程，那种云环境，随便哪儿开网页哪儿就有，我记得码云好像有
3.a. 这一步我有些不懂，许多electron打包的软件自动更新解决方案似乎都是把 babel 和 webpack 的转译/打包交给类似 travis c i处理，发布到github release上后把整个打包好的软件重新下载一遍。
3.b. 其实 electron 可能不需要 babel，反正里面的 chrome v8 是固定版本，谁下载了理论上都能跑吧？

**Comment by langyo** [comment]
嗯...我没有时间整理代码，也没有时间写 doc，并且我还是野路子出身，代码当然不太容易看懂啦...(〃′o`)
不过我还是遵守一些代码规范的，该有注释的地方我都加了注释，没注释的一般都是容易理解的地方(〃′o`)

回到正题
我确实知道有云编程环境，而且我到现在还在用，叫 codesandbox
但这个环境比较鸡肋，它只能调试完完全全前端的东西，也就是 React、Vue 之类的东西，而且没办法正常识别我那个项目比较奇怪的目录结构(你也看到了，scripts 与 native 被分开但居然又互相访问 XD)

然后是有关自动更新保留 bundle 的必要性
你可能不知道 Electron 的尿性...Electron 中的 V8 引擎一般只依赖 bundle 文件，压根就用不到 node_modules 里的东西(而且 node_modules 怪大的，一不小心就占用很大的空间)
所以，我在打包的时候，其实会选择不连带把 node_modules 也打包进去，只打包 bundle，这就足够了，但也因此让客户端自己失去了转译代码的能力
于是留下 bundle 就很有必要了...

**Comment by langyo** [comment]
还有，开机 F8 有密码，这种密码是哪怕信息中心的老师都不知道的，只能问当初维护这些机器的人

你别把学校的电脑想的太简单...那个什么极域电子教室我到现在都仍然要依靠拔网线来解决强制全屏屏幕广播问题...

**Comment by langyo** [comment]
顺带...你帮我看下travis ci...我不太会用...给的指令居然连个最基本的cd切换文件夹都失败...

**Comment by simon300000** [comment]
简单啊，你把硬盘拆出来重装一下装回去

**Comment by langyo** [comment]
(奇怪了 OpenHub 没办法编辑 issues，只能不断回复了)

最后再补充下为什么非得 Babel 转译、 Webpack 打包，才能给 Electron 用...

** 因为  V8 不支持 ES6 语法啊 ** XD

(即使是到了现在的 Chrome 71，也不支持)

**Comment by simon300000** [comment]
async还是支持的（笑

**Comment by simon300000** [comment]
关于那个Electron的问题，我倒是推荐你直接上webpack，不过可能会花好多时间，现在倒也不需要

**Comment by langyo** [comment]
别让我去弄 webpack 了...两个月前为了让这破玩意正常运行，费了两星期的劲...我不想再弄那玩意了...(〃′o`)

**Comment by simon300000** [comment]
hiahiahiahiahiahia
