### ISSUE TITLE
[讨论] 有关开发 Java 插件的决定

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#40]
**简要说明为什么要发起这个讨论**
在重新审视之前的各类插件计划时，发觉 Electron 无法很好的做到例如这样的功能：
- 以框架的形式启动 Java 程序并对其予以监视（换句话讲，无法像 HMCL 那样启动游戏）
- 无法检测到其它的外部程序
- 无法操纵复杂硬件（例如操纵某些高级游戏鼠标上的闪光灯？）
- 无法录屏、录音
- 无法良好的读写压缩文档与二进制文件（也同时为支持存档编辑作铺垫）
- 无法读写本地系统数据库（如 Windows 系统下的注册表等，这是为了留存安装信息、能让系统找到软件的卸载程序等而需要的）
- 无法执行运算量大的任务（你们应该明白 JavaScript 无论优化得再怎么好也快不了哪里去得道理吧？）

为此，我决定启动 Java 插件计划，并同时冻结原本的 Java 启动器/修复器/安装器计划（原因是希望大家能将精力放在更重要的事情上）

  **详细的讨论大纲或正文**
改决定对应的具体任务表将于一星期内发放到内部 TIM 讨论群，对应于一部分已在本项目 projects 中插件计划 project 的一部分内容。

  **补充的细节**
开发的方式其实很简单：命令行程序。
你没听错，不要 GUI，真的只是命令行程序（当然了，有一部分诸如截图等这类是必须要 GUI 的，但做完自己的事情后也立即退出程序）。
这有点像 Linux 下的各种小工具，例如，我想给客户端加个点击按钮进行截图然后自动连同日志打包上传到论坛附件的功能：
```
# 设置 JRE path 路径
set path="..."
# 进入插件文件夹（插件的源代码肯定不会在 env 下了）
cd plugins/java/
# 运行截图
javac screenshoot.jar -path "./screenshoots/" -name "latest.png"
# 运行打包程序
javac packageZIP.jar -files "./screenshoots/latest.png" "./.minecraft/logs/latest.log" -package "./temp/updating.zip"
```

  **其它要说的话**
@simon300000 @Yaossg @jihuayu @euOnmyoji @InitAuther97

**Comment by InitAuther97** [comment]
this is eaaaaaaaaaaaaaasy to make but I need to finish my things first such as fucking 1000-meter run……I am dead.

**Comment by InitAuther97** [comment]
Just a mistake qwq

**Comment by simon300000** [comment]
别问 问就是Buffer

**Comment by jihuayu** [comment]
所以是啥意思？改成java开发整个项目？

**Comment by langyo** [comment]
> 所以是啥意思？改成java开发整个项目？

有一部分本地功能拿 Java 写而已……没有全部整改的意思……
