### ISSUE TITLE
[讨论] 针对架构的大批量更改

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#41]
**详细的讨论大纲或正文**
- 添加“浏览器端”
对于桌面版，除了可以选择启动一个 Electron 进程以外，还可以选择启动单独的 Node 守护进程，就像蓝灯那样（前端以用户自己的浏览器查看，后端运行一个 Node 程序）
这样以来，客户端便能以类似蓝灯那样的方式启动（虽然其实这是一种备选的启动方案），并且也因此能彻底做到 UI 控制部分与非浏览器能办到的实体功能分开（不过平台无关的 UI 控制部分还需要写额外的代码用于判断是在什么环境下运行）
也因此，不同平台（甚至可能包括移动版）运作的 index.html 实际内容是不同的：
    - Electron 端的 index.html 负责与主进程创建 IPC 通道与一些供平台无关代码调用的全局函数
    - Node.js 端（浏览器页面守护进程）负责启动服务端的端口监视与启动浏览器，所以 index.html 中与 Node.js 端通信的方式是内部的网络 HTTP 请求
    - Ionic 与 Electron 类似，但由于可能无法像 Electron 那样创建可用于调动底层的 IPC，或像 Node.js 端那样可以创建本地服务端，所以比较麻烦，以后再说（可以充分利用 Ionic 的插件优势；如果 Ionic 行不通，会重回 React Native 方案，甚至可能会选择完全重写）

- 原来在 native/electron/localScript 中的内容也被扣走、并入 script 中（这也意味着桌面版与移动版的界面现在同源了）；如果 electron 需要写主进程代码，放在 src 文件夹中（Node.js 端也这么做）

- 所有 Native 端至少（也至多）需要提供给平台无关部分代码的 API：
    - nativeCall（提供名称、参数列表和回调函数，返回一个 EventEmitter；对于 Electron 以及 Node.js 端，等同于启动对应的 Java 程序，并建立与 Java 程序的通讯）（通讯方式为本地的 C/S 连接，Node.js 作为客户端，Java 部分作为服务端）
    - HTTP(S) 网络操作（以 Node.js 本地方法做）
    - Files 文件操作（以 Node.js 本地方法做）
    - System（提供诸如程序退出、收集日志等服务；console.log 会被为此覆盖）
    - Server 驻留服务（用于创建系统托盘、显示通知等，这个在 Electron 端应该没问题，但如果纯 Node.js 得需要额外的 Java 插件支持）
- 更新了主界面的 UI
现在你们暂时可以在这里看到：https://codesandbox.io/s/qxpvqq8w

这部分更改马上就做，先跟你们说一声，不然我大改项目之后你们云里雾里的，不好协作

这部分如果写好了，版本会直接升级到 0.3.0，因为架构大改

  **其它要说的话**
@simon300000 @Yaossg @euOnmyoji @InitAuther97 @jihuayu

**Comment by okboy5555** [comment]
有没有联系方式
