### ISSUE TITLE
[问题]Node.js、Java本地通信标准与游戏启动、游戏插件

### ISSUE THREAD

**Issue by InitAuther97** [langyo/MCBBS-Client#42]
Node.js与Java经验证可以直接使用Socket通信。
现在需要一个标准，包括数据的序列化传输，数据序列化后标准格式。
之前你说要与Java部分交互，Socket通信是个极佳的方法
——————————
另外的，热启动mc不好实现，只能启动另一个java进程负责mc，
不然启动器本身会吃进去接近4-6G的内存，友好先不说，用是不可能了
之前说写一个shell启动Minecraft是一个极佳的方法，可以把命令行参数
在shell里设置之后启动，而shell可以退出自己或者等待崩溃弹出窗口
——————————
游戏的插件问题，可以选择用
js(best,has function,easy to write)
json(有现成的一个写到一半的读取器)(还是？？？)
hocon(will be excellent to work with js!)
xml(kidding??????????)，这是几个目前我用api可读的
极其推荐hocon+js 虽hocon有多种书写标准， 但都可读写
而且hocon常用配置文件，非常简洁（虽说这种做法可能是第一次）可做主类文件！
支持include和继承(可能是我见过最nb的配置文件语言)是我认为比较好的地方
用hocon+js到时候就可以很简单的发布插件开发包了(???)
——————————
ly辛苦注意身体QAQ

**Comment by InitAuther97** [comment]
Please not close until langyo replys all of these!

**Comment by InitAuther97** [comment]
这几个简洁方便(???)的语言都存在无法和java正常交互(js还可以比较简单的复杂交互)的问题

**Comment by InitAuther97** [comment]
还有，Socket服务器由Java端打开

**Comment by langyo** [comment]
给我三天时间，我会将标准全部放出来

最近我可能无法推送代码，但我的工作一直在做，现在需要先打草稿

这个 issue 不要关，我后面会回复

**Comment by simon300000** [comment]
Socket服务器可以Nodejs开，
可以用
https://github.com/socketio/socket.io
https://github.com/socketio/socket.io-client-java

**Comment by simon300000** [comment]
我推荐使用JSON/object

**Comment by simon300000** [comment]
需要的话，Nodejs和Socketio都是支持Buffer的

**Comment by langyo** [comment]
> 还有，Socket服务器由Java端打开

Node 与 Java 都将打开一个 socket 通道，具体原因等我把发送的消息格式与原理给你看你就明白了

**Comment by simon300000** [comment]
哎？那谁当server？

**Comment by langyo** [comment]
两边都当 server，两者的交流将只有主动与被动之分，主动者为 client，被动者为 server

**Comment by simon300000** [comment]
据我所知Websocket基于http握手的
拿谁来当http，谁发起请求？

**Comment by langyo** [comment]
...你可能搞错我的意思了

我得纠正下，不是 Electron 与 Java 直接通讯，而是 Node 服务进程与 Java 通讯

你肯定想问我，Electron 不就是 Node 么？

其实不是...我计划 Electron 那里将完全不使用本地功能，最多动用 H5 的 API罢了；与此同时，发起一个无任何 UI 层参与的 NodeServer 项目，所有不能在 H5 做的事情都会在这里做（例如读写文件、发起无限制的 HTTP 请求等）

也因此，Electron 中的页面需要与 NodeServer 通讯，这时候才会用到 WebSocket，而 ws 方面，Node 进程为服务端

至于为什么这么做...我在为移动版作铺垫，尽可能将平台无关与平台相关的部分分离开来，这样子不仅能节省后续移动版的开发成本，也能使得代码层次更清晰

**Comment by simon300000** [comment]
本来早该怎么搞了。。。

所以Node是服务端，Java是客户端咯
不过既然是electron和NodeServer，为什么不用ipc？

**Comment by langyo** [comment]
> 本来早该怎么搞了。。。
> 
> 所以Node是服务端，Java是客户端咯
> 不过既然是electron和NodeServer，为什么不用ipc？

原因很简单，在 Electron 用的 API 不能在其他地方用，一旦迁移到只能提供 H5 浏览器壳子的平台就没有任何其它的本地 API 可以用了，但通过让网页只做与外界通讯这一件事则保留了这个可能 

说实话，确实，什么事情完全只交给 Java 启动个服务端就行了，但是，拿 Java 写诸如启动 Shell、操作文本文件等操作，真的是杀鸡用牛刀，往往要写出比实现同样功能的 Node 代码的好几倍的量才能完成 

另一方面，Java 不直接支持 WebSocket，我要自己写专门的套结程序又很麻烦，我不想为此增加一批 Java 的依赖仓库，毕竟项目已经够复杂的了，再加新的东西的话，我都没法续

**Comment by InitAuther97** [comment]
我只想问为什么不能一个socket双向通信呢？服务器交给Java来多方便,还是你想这样之后添加内容方便？

**Comment by InitAuther97** [comment]
还有 准备一套node与java握手方案 防止有人硬核破解某些后续功能

**Comment by langyo** [comment]
> 我只想问为什么不能一个socket双向通信呢？服务器交给Java来多方便,还是你想这样之后添加内容方便？

因为端口冲突

不信你试试，分别运行（java 先编译）demos/sockets 中的 java-server 与 node-server（把两个程序注册的端口都改成同一个数字，我相信你哪怕没学过 js 也好歹能找到数字），同时运行

这时你会发现其中一个弹出错误（哪个后运行哪个出错），提示端口被占用

以及，node 与 java 的握手我也早就想好了，有专门的指令，马上就随着指令集文档一起给你们看

（必要时，这个握手可以重复握，以进入加密数据交流模式，这样子密码什么的就不用太慌了）

**Comment by InitAuther97** [comment]
> 因为端口冲突
不信你试试，分别运行（java 先编译）demos/sockets 中的 java-server 与 node-server（把两个程序注册的端口都改成同一个数字，我相信你哪怕没学过 js 也好歹能找到数字），同时运行
这时你会发现其中一个弹出错误（哪个后运行哪个出错），提示端口被占用
以及，node 与 java 的握手我也早就想好了，有专门的指令，马上就随着指令集文档一起给你们看
（必要时，这个握手可以重复握，以进入加密数据交流模式，这样子密码什么的就不用太慌了）

java-server搭配node-client不行吗(痴呆

**Comment by langyo** [comment]
> > 因为端口冲突
> > 不信你试试，分别运行（java 先编译）demos/sockets 中的 java-server 与 node-server（把两个程序注册的端口都改成同一个数字，我相信你哪怕没学过 js 也好歹能找到数字），同时运行
> > 这时你会发现其中一个弹出错误（哪个后运行哪个出错），提示端口被占用
> > 以及，node 与 java 的握手我也早就想好了，有专门的指令，马上就随着指令集文档一起给你们看
> > （必要时，这个握手可以重复握，以进入加密数据交流模式，这样子密码什么的就不用太慌了）
> 
> java-server搭配node-client不行吗(痴呆

...等会我放出来指令的工作原理你就明白为什么我非得开两个端了

**Comment by InitAuther97** [comment]
> 我推荐使用JSON/object

但js是java支持最好的其他类型语言，还有自带的执行引擎，插件类首选还是这个 json局限性过大我才标三个问号
因为没有函数的支持，其它语言可以说与js差了不止一步 而且由于nashorn的特性可以直接从js调用java端方法也是强大无比了
纯js也不是不可以，但是可以考虑hocon可以更加方便书写

**Comment by langyo** [comment]
> > 我推荐使用JSON/object
> 
> 但js是java支持最好的其他类型语言，还有自带的执行引擎，插件类首选还是这个 json局限性过大我才标三个问号
> 因为没有函数的支持，其它语言可以说与js差了不止一步 而且由于nashorn的特性可以直接从js调用java端方法也是强大无比了
> 纯js也不是不可以，但是可以考虑hocon可以更加方便书写

https://github.com/langyo/MCBBS-Client/blob/master/docs/wiki/socketCommands.md

@InitAuther97 @simon300000 @Yaossg @euOnmyoji @jihuayu 

指令协议出炉了，各位看一下

明后天我可能无法正常开工，但我会开始积攒代码的

另外，有关 Init 的 js 执行引擎的问题，我虽然十分清楚 java 有能执行 js 的能力（并且效果应该还不错），但也有以下的劣势：
- 没有如同 Node 那样全面且恐怖的 API，如果确实要用，很多函数都得我们自行注册、实现那些我们需要的功能
- 运行速度比起原生的 Node 速度要慢很多，毕竟这是 JVM，不是拿原生的以 C++ 编译的字节码运行的
- 如果 Java 版本过低，很可能不支持一些太先进的 ECMA 标准，有些特殊的语法将很可能报错无法执行
所以我才选择 Node 与 Java 并驾齐驱是最优先的方案

**Comment by simon300000** [comment]
所以为什么要两个端口？？？我懵逼了
还是不懂

**Comment by langyo** [comment]
> 所以为什么要两个端口？？？我懵逼了
> 还是不懂

因为端口会被占用啊……

如果你是想说只凭一对 C/S 维护这个通信，那这个指令的复杂度将大大提升，并且其中一边也得不断轮询对方

**Comment by langyo** [comment]
经过一晚上的讨论，该决议正式生效，参照 https://github.com/langyo/MCBBS-Client/blob/master/docs/wiki/socketCommands.md 进行相关编写
@InitAuther97 继续负责 native/javaServer，写 socket 通讯协议与插件加载接口
@simon300000 准备负责 natove/electron 中与 node 交互的 ws，现在暂时不用动工
