### ISSUE TITLE
[讨论] 从现在起，请直接修改源仓库

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#44]
**简要说明为什么要发起这个讨论**
经过了三天的积攒，我基本上在纸上完成了所有的 Java 端的服务代码，但现在还没来得及录入。
不过令我懵逼的是，你们同时也有了动作……而且如果没看错的话，你们在实现和我之前已经写好的功能……
![50f06b6d261a05729e866.png](https://miao.su/images/2019/04/21/50f06b6d261a05729e866.png)
所以……你们还是直接往源仓库推送吧……

P.S. 我今天下午会尽可能将所有的已经积攒的代码都推送上来，目前的推送可以参考我[这次commit](https://github.com/langyo/MCBBS-Client/commit/bf658a399db8e7e3877d06ffd3a3988580344a10)

  **其它要说的话**
@InitAuther97 @euOnmyoji @Yaossg

**Comment by InitAuther97** [comment]
alright

**Comment by InitAuther97** [comment]
我把两个合并一下 因为用我的api看起来会让操作简单不少
