### ISSUE TITLE
[特性]关于客户端插件加载

### ISSUE THREAD

**Issue by InitAuther97** [langyo/MCBBS-Client#47]
鉴于目前插件加载机制
只能在命令行指定主类
或者在程序内硬制定
或者交给上天碰运气看他老人家愿不愿意加载 发个火就能让插件作者前功尽弃跪着喊祖宗
我想要添加一个类似于manifest的机制，通过plugin.*(配置文件)来加载插件主类和配置插件信息

一个yaml api,或者什么也不需要 对应三种配置文件格式(yml properties js)

不要json xml	编写太复杂了

ly辛苦

**Comment by InitAuther97** [comment]
是时候来讨论一下配置文件是js还是yml还是properties了

**Comment by InitAuther97** [comment]
js format:function main(){return "net.mcbbs.client.plugin.clipboard.TestPlugin"}; function name(){return "Clipboard api"}; function id(){return "clipboard"}; function on(cmd){};

**Comment by InitAuther97** [comment]
yml format:

**Comment by InitAuther97** [comment]
yml format:cfg:\n\t id: clipboard \n\t main: net.mcbbs.client.plugin.clipboard.TestPlugin \n\t name: clipboard api \n\t on: \n\t\t get: {$main}.ClipboardGetter do

**Comment by InitAuther97** [comment]
properties: main=net.mcbbs.client.plugin.clipboard.TestPlugin \n name=Clipboard api \n id=clipboard on.get={$main}.ClipboardGetter do

**Comment by langyo** [comment]
你写好具体的代码，然后在这里回复你所补充的代码的位置

**Comment by langyo** [comment]
你尽快合并……因为我等下也很可能要开始改我之前的实现了……

我注意到我的代码可移植性太差了，只能支持对 Node 一个的对点 Socket，所以我得多写一些，好歹让它能支持多端通讯
