### ISSUE TITLE
[讨论]更改Java-Node通信方式

### ISSUE THREAD

**Issue by InitAuther97** [langyo/MCBBS-Client#48]
基于可能多条指令需要等待上天安排哪个指令先执行，我建议增加一个请求之id

事实上，按照目前ly的安排，一个命令打开一个socket对当前ly自己的写法不怎么友好，我建议在客户端启动时Java建立一个Server在9233,然后node与java建立一个持续性连接然后在命令某个位置表示cmdId(或者包装成json,{"id":xxx,"cmd":"..."})

ly可以等期中考之后再来处理这堆烂摊子

**Comment by langyo** [comment]
我的想法比你的更简单：所有服务端的锅都由 Node 背，H5、Java 均只要做连接这件事就行了

并且，由于统一 WebSocket，所以协议问题也就直接免了，要加密通信直接加密自己参数就可以了

**Comment by langyo** [comment]
我最近准备改写 Java 部分，将其简化为我之前的那个新的指令架构

**Comment by InitAuther97** [comment]
> 我最近准备改写 Java 部分，将其简化为我之前的那个新的指令架构
行，留个注册Command的接口

**Comment by InitAuther97** [comment]
> 我最近准备改写 Java 部分，将其简化为我之前的那个新的指令架构

行，留个接口来注册Command
