### ISSUE TITLE
[特性]客户端部分正版登录

### ISSUE THREAD

**Issue by InitAuther97** [langyo/MCBBS-Client#49]
为了给正版玩家更好的游戏体验和不让正版玩家因为不能正验而放弃客户端，我已经添加了外部yggdrasil验证，现在需要从客户端登录正版账号

一个按钮，在客户端里
一个传输规范

**Comment by langyo** [comment]
我这几天会给你具体要注册的指令，现在我 ws 通讯的 Node 部分刚成功运行，需要时间进行测试

**Comment by langyo** [comment]
现在给你流程，

Java 端先尝试连接 Node 端，或 H5 尝试连接 Java 端：

```execute system register h5/java```

成功后对方应当回复一个：

```data system register ok```

然后 H5 这里点击启动游戏后，会发送指令：

```execute minecraft launcher launch <gameVersion> <userID>```

如果成功，Java 端得先回个：

```data minecraft launcher launch success```

然后 Java 端会定时发回一些游戏日志：

```data minecraft launcher launch log XXXXXX```

当然了，在此之前必须先注册一个有效的游戏名，所以在启动之前 H5 会发给你个这样的东西：

```execute minecraft launcher setting user add -username XXX -loginMethod Mojang/Logout/Yggdrasil -password XXX```

如果成功， Java 端应该回个：

```data minecraft launcher setting user add success XXX```

上头那个 XXX 才是真实的 ID，启动的时候应当传这个；你可以回个 UUID

以及就是指定游戏版本的问题：

```execute minecraft launcher setting game add 1.13 --extra Forge 1.13.XXXX --extra Optifine HD-XXX```

上头也是像用户名那样回个 ID，UUID 是可以的

H5 可以通过以下的指令获取已经注册的游戏名和用户名：

```execute minecraft launcher get user name XXX```

```execute minecraft launcher get game name XXX```

其中的 XXX 是你之前给的 ID

当然了，get 不仅能 get 名字，还可以 get 一些具体的信息，例如我要 get 某个账户信息的登录方式，或是某个游戏端装载的 Forge 版本：

```execute minecraft launcher get user loginMethod XXX```

```execute minecraft launcher get game extra Forge XXX```

然后每次客户端重新启动时，为了获取游戏名 ID 与用户名 ID 名单，需要执行 list 指令：

```execute minecraft launcher list user/game```

Java 端返回的东西大致是这样的：

```data minecraft launcher list user/game XXX XXX XXX XXX...```

大概是这个样子，总之需要遵循 2R1S 的模式就是了

另外，每条指令执行完后必须再传个换行；我们的通讯器通过换行来识别指令是否结束

**Comment by simon300000** [comment]
想起了kcp

**Comment by InitAuther97** [comment]
统一格式 不然没法模块化

**Comment by InitAuther97** [comment]
统一格式execute pkgName namespace func [args]
data同上 不过在args前多了个data
pkgName是java端插件名称 namespace可以分隔功能区 func为一函数 args是参数 用--开始，键值对
minecraft插件我已经做好框架了，晚上上传
minecraft
       -launcher
              launch:boolean
              version <version:string>:boolean
       -game
              log <log:string>:void
              shutdown <reason:string>:boolean
              blockFor:void throws BlockingInterruptedException
        -plugin
              install <plgName>

**Comment by langyo** [comment]
> 统一格式execute pkgName namespace func [args]
> data同上 不过在args前多了个data
> pkgName是java端插件名称 namespace可以分隔功能区 func为一函数 args是参数 用--开始，键值对
> minecraft插件我已经做好框架了，晚上上传
> minecraft
> -launcher
> launch:void throws LaunchException
> version version:string :boolean
> -game
> log log:string :void
> shutdown reason:string :boolean
> blockFor:void throws BlockingInterruptedException
> -plugin
> install plgName:String :void throws PluginException
> uninstall plgName:String :void throws PluginException
> list kind:String[installed,all] :Array

没别的意见，唯一的要求是，指令必须写在同一行，因为 ws 通讯设施依赖换行来确定是否结束一条指令

**Comment by InitAuther97** [comment]
> 没别的意见，唯一的要求是，指令必须写在同一行，因为 ws 通讯设施依赖换行来确定是否结束一条指令

当然可以，那么就按照这个填充内容了

**Comment by InitAuther97** [comment]
close就先别了 因为这个 issue 我想等到制作完正版登录和启动再close

**Comment by InitAuther97** [comment]
2R1S架构什么来着，我给忘了....

**Comment by langyo** [comment]
> 2R1S架构什么来着，我给忘了....

https://github.com/langyo/MCBBS-Client/blob/master/native/desktop/server/pluginDashboard.js

**Comment by langyo** [comment]
新的额外命令格式(json)

```json
json命令格式
{
"type":Enum{"execute"|"data"},
"module":String,
"namespace":String, //可空，如果为空，下面的 method 就属于一个名字为空字符串的命名空间
"method":String,
"args":Array<String>
}
```

**Comment by langyo** [comment]
### 启动器命令格式大纲
logout提供username:USERNAME,password:PASSWORD 正常执行返回值args是个空数组
refresh提供access_token:ACCESSTOKEN 返回新的accessToken
validate提供access_token:ACCESSTOKEN,如果accesstoken可用返回空 暂时不可用期和不可用期返回ForbiddenOperationExcoetion
还有一个invalidate 提供access_token:ACCESSTOKEN 执行成功就不返回 执行失败返回ForbiddenOperationException
login是登入 logout是登出 refresh是刷新at状态 validate验证at是否可用 invalidate无效化at

**Comment by InitAuther97** [comment]
// json命令格式
{
"id":"UUID parsed from time",
"type":Enum{"execute"|"data"},
"module":String,
"namespace":String, //可空，如果为空，下面的 method 就属于一个名字为空字符串的命名空间
"method":String,
"args":Array<String>
}
