### ISSUE TITLE
[讨论] 新的开发方式——必须向对应子分支推送代码

### ISSUE THREAD

**Issue by langyo** [langyo/MCBBS-Client#57]
所有现役开发者请注意，客户端即将进行分支改造，将会分出以下分支：
```
native-desktop-electron
native-desktop-node
native-desktop-java
native-desktop-cs
native-desktop-cpp
native-mobile-cordova
src
res
website  // 客户端的前端宣传网站，一般不与其它分支合并
dev  // 开发分支，所有当前的开发成果请向这里合并
master  // 根分支，请勿动它
```

请所有开发者不要直接向 dev 与 master 分支推送代码，而是根据自己开发的内容不同，向对应的分支推送代码，待完成一段功能后再向 dev 分支发起合并请求；master 请求谁也别动

对应的分支将会在三天内全部建立并初始化完毕，在此之前有什么修改意见请尽快提出

顺带一提，这么改过之后，大家的提交习惯也得跟着改改，这是为了保证各人修改不互相冲突；所有人在 push 时都必须以 rebase 方式上传（什么是 rebase 自己搜，反正这种机制挺好的）

@simon300000 @forestbat @Yaossg @euOnmyoji @InitAuther97 @jihuayu @okboy5555

**Comment by InitAuther97** [comment]
batch做好了，试试看？

**Comment by InitAuther97** [comment]
batch做好了，试试看？

**Comment by InitAuther97** [comment]
学校里呢，走了走了，信息课

**Comment by langyo** [comment]
我在考虑采用 @simon300000 的方案，分割这个项目到一大堆子仓库中，再用 git submodule 整合

别的应该没太大问题，唯一遗憾的地方，就是如果这么做，所有先前开发所作的贡献代码量将会被清空（因为是代码迁移）

还得从长计议

**Comment by simon300000** [comment]
> 我在考虑采用 @simon300000 的方案，分割这个项目到一大堆子仓库中，再用 git submodule 整合
> 
> 别的应该没太大问题，唯一遗憾的地方，就是如果这么做，所有先前开发所作的贡献代码量将会被清空（因为是代码迁移）
> 
> 还得从长计议

这个submodule似乎不能真的解决所有问题→_→ 我也不清楚目前有什么问题

**Comment by InitAuther97** [comment]
alright then

**Comment by langyo** [comment]
submodule 方案已实行，现已建立用于容纳分管仓库的小组

一星期内会部署完成

**Comment by langyo** [comment]
部署完成
