### ISSUE TITLE
关于Travis Ci打包发布

### ISSUE THREAD

**Issue by simon300000** [langyo/MCBBS-Client#7]
### release上传文件

https://github.com/langyo/MCBBS-Client/blob/4a6c28cc2109b980a737b4d4bdee31d9169a0974/.travis.yml#L37

这一行，是指release时上传的文件，我写的dist时因为那是我打包的文件，你可能需要参照：https://docs.travis-ci.com/user/deployment/releases#uploading-multiple-files 来判断→_→

### 多系统同时release

而且现在这样配置可能会有个问题，就是osx和windows两个虚拟机会同时发布两个release。所以我推荐你暂时把deploy设置放在`os: windows`下面，这样osx就暂时不会release。（没人用233

以后想要两个系统一起release可能会有点麻烦，需要用https://docs.travis-ci.com/user/build-stages/

#### 条件性release

还有条件性release https://docs.travis-ci.com/user/deployment#conditional-releases-with-on

建议加上这个条件性release和版本号，免得你写一个commit就一个新版本release，很懵逼。

#### 版本号

关于版本号，大概可以参考git flow？

类似主要在branch develop进行工作，要推新版本就：1.版本号+1； 2.往master merge

然后单元测试都会测，但是仅仅release master

**Comment by langyo** [comment]
你帮我改一下呗，我不太会调，持续集成这东西，我也是最近才刚接触

现在人在外头，不太方便弄

**Comment by langyo** [comment]
@simon300000 我尝试修改了下 .travis,yml，更正了上载路径，但还是不行，似乎有别的问题

另外，还请帮我看一下如何正确设置条件发布 release，我看到文档里有 tag 啥的能够控制这种过程，但 tag 在哪加我都不知道

**Comment by simon300000** [comment]
给你看看一套我装机的代码：@langyo 
```sh
defaults write com.apple.dock mineffect suck #窗口最小化特效 吸入
defaults write com.apple.finder QLEnableTextSelection -bool TRUE #更好用（不确定生不生效
defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES #Finder上面显示路径
defaults write com.apple.finder AppleShowAllFiles TRUE #显示隐藏文件
defaults write com.apple.Dock showhidden -bool YES #隐藏的窗口在Dock有半透明特效来着
killall Dock #重启Dock
killall Finder #重启Finder

sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" #装ohmyzsh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" #装brew
```

**Comment by langyo** [comment]
> 终端可以改成zsh（好用也好看
> <img alt="image" width="662" src="https://user-images.githubusercontent.com/12656264/51820126-c221fe00-230f-11e9-864f-5ff7a60bec62.png">
> 
> 给你看我装机的命令：@langyo
> 
> ```shell
> defaults write com.apple.dock mineffect suck #窗口最小化特效 吸入
> defaults write com.apple.finder QLEnableTextSelection -bool TRUE #更好用（不确定生不生效
> defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES #Finder上面显示路径
> defaults write com.apple.finder AppleShowAllFiles TRUE #显示隐藏文件
> defaults write com.apple.Dock showhidden -bool YES #隐藏的窗口在Dock有半透明特效来着
> killall Dock #重启Dock
> killall Finder #重启Finder
> 
> sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" #装ohmyzsh
> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" #装brew
> ```
> 
> 之后装软件可以用Homebrew, 比如node.js ：`brew install node`
> Chrome: `brew cask install google-chrome`
> 升级什么也很方便
> 
> 需要可以换清华源：
> 
> ```shell
> cd "$(brew --repo)"
> git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
> 
> cd "$(brew --repo)/Library/Taps/homebrew/homebrew-core"
> git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
> 
> echo 'export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles' >> ~/.zshrc
> source ~/.zshrc
> 
> brew update
> ```

我得费点时间去试试……你给的 command + R 好像不太管用……我得费点时间解决这个问题

**Comment by langyo** [comment]
> 终端可以改成zsh（好用也好看
> <img alt="image" width="662" src="https://user-images.githubusercontent.com/12656264/51820126-c221fe00-230f-11e9-864f-5ff7a60bec62.png">
> 
> 给你看我装机的命令：@langyo
> 
> ```shell
> defaults write com.apple.dock mineffect suck #窗口最小化特效 吸入
> defaults write com.apple.finder QLEnableTextSelection -bool TRUE #更好用（不确定生不生效
> defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES #Finder上面显示路径
> defaults write com.apple.finder AppleShowAllFiles TRUE #显示隐藏文件
> defaults write com.apple.Dock showhidden -bool YES #隐藏的窗口在Dock有半透明特效来着
> killall Dock #重启Dock
> killall Finder #重启Finder
> 
> sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" #装ohmyzsh
> /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" #装brew
> ```
> 
> 之后装软件可以用Homebrew, 比如node.js ：`brew install node`
> Chrome: `brew cask install google-chrome`
> 升级什么也很方便
> 
> 需要可以换清华源：
> 
> ```shell
> cd "$(brew --repo)"
> git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
> 
> cd "$(brew --repo)/Library/Taps/homebrew/homebrew-core"
> git remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
> 
> echo 'export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles' >> ~/.zshrc
> source ~/.zshrc
> 
> brew update
> ```

我现在已经通过抹除磁盘的方式重装了系统，你给的指令我用了下，除了 Brew 以及其对应的一些东西因为网络原因没法下好（我这里连接 github 奇慢无比），别的都调试的差不多了

多谢🙏

**Comment by langyo** [comment]
不行，没用，我重新生成了 API key，还是失败 @simon300000

**Comment by simon300000** [comment]
我今晚/明日拿我的fork试试看→_→

**Comment by simon300000** [comment]
我这里倒是木有问题。。。很迷
https://github.com/simon300000/MCBBS-Client/releases/tag/untagged-3d1a1566c63e3ab85896
https://travis-ci.org/simon300000/MCBBS-Client/jobs/486551256
https://github.com/simon300000/MCBBS-Client/blob/travis-test/.travis.yml#L38-L40

**Comment by langyo** [comment]
暂时不使用 Travis CI 去打包东西了……我现在已经回归 Windows 环境（可能会尝试黑苹果）

后续有需要我再 at 你吧……
